from pathlib import Path
import sys
root=Path(sys.argv[1] if len(sys.argv)>1 else '_site')
p=root/'index.html'
s=p.read_text('utf-8')

def must_replace(old,new,label):
    global s
    if new in s: return
    if old not in s: raise SystemExit(f'patch target not found: {label}')
    s=s.replace(old,new,1)

old='''        <div class="account-card"><h3>学生云端登录</h3><p>旧学生可以继续使用原来的 4 位 PIN；新账号建议使用 6 位 PIN。首次云端注册后，本机已有的 XP、R积分、打卡、头像、徽章和训练记录会自动迁移。法则实验室、闯关训练和数圈侦探均需先完成学生云端登录。</p>
          <div class="identity-grid"><div class="identity-field"><label for="accountClassInput">班级码</label><input id="accountClassInput" maxlength="12" placeholder="如 ZY2901"></div><div class="identity-field"><label for="accountStudentInput">学号 / 代号</label><input id="accountStudentInput" maxlength="24" placeholder="如 17"></div><div class="identity-field pin"><label for="accountPinInput">4 或 6 位 PIN</label><input id="accountPinInput" inputmode="numeric" maxlength="6" type="password" placeholder="••••••"></div></div>
          <div class="cloud-field full"><label for="accountNameInput">公开昵称（同学可见，可不填）</label><input id="accountNameInput" maxlength="24" placeholder="如 17号小方"></div>
          <div id="accountError" class="student-error"></div><div class="account-actions"><button id="logoutBtn" class="ghost">退出当前学生</button><button id="localLoginBtn" class="ghost">仅本机进入</button><button id="cloudRegisterBtn" class="ghost">首次云端注册</button><button id="accountLoginBtn" class="primary">云端登录 →</button></div><div class="local-note">云端登录后以云端为主；每次游戏结束会自动同步。本机仍保留一份缓存，断网时可以继续使用，恢复网络后再次同步。</div>
        </div>'''
new='''        <div class="account-card"><h3>学生云端登录</h3><p>学生账号由教师统一创建。用户名固定为“班级码-学号”，例如 <b>ZY2901-17</b>。第一次使用教师发放的临时密码登录后，必须设置自己的新密码，完成后才能进入训练。</p>
          <div class="identity-grid"><div class="identity-field"><label for="accountUsernameInput">用户名</label><input id="accountUsernameInput" maxlength="64" autocomplete="username" placeholder="如 ZY2901-17"></div><div class="identity-field pin"><label for="accountPasswordInput">密码 / 初始密码</label><input id="accountPasswordInput" maxlength="32" type="password" autocomplete="current-password" placeholder="请输入密码"></div></div>
          <div id="accountError" class="student-error"></div><div class="account-actions"><button id="logoutBtn" class="ghost">退出当前学生</button><button id="accountLoginBtn" class="primary">学生登录 →</button></div>
          <div id="firstPasswordBox" class="cloud-hidden" style="margin-top:14px;padding:14px;border:2px solid rgba(62,53,64,.16);border-radius:14px;background:#fffdf8"><b>首次登录 · 设置自己的密码</b><p style="margin:6px 0 10px">新密码设置后，老师无法查看；忘记时由老师重置为新的临时密码。</p><div class="cloud-fields"><div class="cloud-field"><label for="firstNewPassword">新密码（6–32位）</label><input id="firstNewPassword" type="password" maxlength="32" autocomplete="new-password"></div><div class="cloud-field"><label for="firstNewPassword2">再输入一次</label><input id="firstNewPassword2" type="password" maxlength="32" autocomplete="new-password"></div></div><div class="cloud-actions"><button id="setFirstPasswordBtn" class="primary">保存新密码并进入</button></div><div id="firstPasswordMsg" class="cloud-msg"></div></div>
          <div class="local-note">云端账号是唯一训练身份；本机仅保留缓存和旧数据迁移，不再允许学生自行创建账号。</div>
        </div>'''
must_replace(old,new,'student account card')

old='<div id="teacherDashboard" class="cloud-wall cloud-hidden"><div class="cloud-wall-head"><div><div class="eyebrow">TEACHER DASHBOARD</div><h3>班级进度</h3></div><select id="teacherClassSelect"></select></div><div id="teacherTable" class="teacher-table"></div></div>'
new='''<div id="teacherDashboard" class="cloud-wall cloud-hidden"><div class="cloud-wall-head"><div><div class="eyebrow">TEACHER DASHBOARD</div><h3>班级账号与进度</h3></div><select id="teacherClassSelect"></select></div><div class="cloud-card" style="margin:12px 0"><h3>统一创建学生账号</h3><p>输入学号列表，支持 <b>1-45</b> 或用逗号、空格、换行分隔。系统会生成“班级码-学号”用户名和一次性初始密码。</p><textarea id="bulkStudentCodes" rows="4" style="width:100%;border:2px solid rgba(62,53,64,.24);border-radius:12px;padding:10px;font:inherit" placeholder="例如：1-45&#10;或：1,2,3,4,5"></textarea><div class="cloud-actions"><button id="bulkCreateStudentsBtn" class="primary">批量创建学生</button><button id="copyCredentialsBtn" class="ghost">复制本次账号表</button></div><div id="teacherProvisionMsg" class="cloud-msg"></div><div id="teacherCredentials" class="teacher-table"></div></div><div id="teacherTable" class="teacher-table"></div></div>'''
must_replace(old,new,'teacher dashboard')
s=s.replace('<b>不会公开：</b>PIN、登录凭证和其他班级数据。','<b>密码规则：</b>学生当前密码不会以明文保存，也不会向教师显示；教师只能重置为新的临时密码。<br><b>不会公开：</b>登录凭证和其他班级数据。',1)
s=s.replace("function cloudStudentReady(){try{return !!(cloudState?.user&&cloudState?.role==='student')}catch(e){return false}}","function cloudStudentReady(){try{return !!(cloudState?.user&&cloudState?.role==='student'&&!cloudState?.mustChangePassword)}catch(e){return false}}",1)
s=s.replace("$('#accountClassInput')?.focus();","$('#accountUsernameInput')?.focus();")
s=s.replace("const cloudState={user:null,role:'',classId:'',className:'',displayName:'',syncTimer:null,applying:false,pendingPage:''};","const cloudState={user:null,role:'',classId:'',className:'',displayName:'',syncTimer:null,applying:false,pendingPage:'',mustChangePassword:false,username:''};",1)
s=s.replace("pr?.display_name||$('#accountNameInput').value.trim()||`${id}号小方`","pr?.display_name||cloudState.displayName||`${id}号小方`",1)
s=s.replace("let res=loginOrCreate(cls,id,$('#accountPinInput').value);if(res.ok)await cloudSyncProfile(res.profile,true);","let db2=loadDB(),key2=makeProfileKey(cls,id),p2=db2.profiles[key2]?ensureProfileShape(db2.profiles[key2]):blankProfile(cls,id,'');db2.profiles[key2]=p2;db2.current=key2;saveDB(db2);state.profileKey=key2;state.classCode=cls;state.studentId=String(id);refreshPlayerUI();await cloudSyncProfile(p2,true);",1)

start=s.index('  function renderAccount(){')
end=s.index('  const CLOUD_URL=',start)
s=s[:start]+r'''  function renderAccount(){const db=loadDB(),p=currentProfile(),profiles=Object.entries(db.profiles).map(([k,v])=>[k,ensureProfileShape(v)]).sort((a,b)=>new Date(b[1].updatedAt)-new Date(a[1].updatedAt));$('#profileListNote').textContent=profiles.length?`这台设备已保存 ${profiles.length} 个学生档案。`:'尚未保存学生。';$('#savedProfiles').innerHTML=profiles.length?profiles.map(([k,v])=>{const li=levelInfo(v.xp),un=`${v.classCode}-${v.studentId}`;return `<div class="saved-profile ${db.current===k?'current':''}"><div><b>${un}</b><span>Lv.${li.level} · ${levelTitle(li.level)} · ${v.games} 局 · ${v.xp} XP · ${displayDateLong(v.updatedAt)}</span></div><button data-profile-prefill="${encodeURIComponent(k)}">填入用户名</button></div>`;}).join(''):'<div class="empty">云端登录后，本机缓存会出现在这里。</div>';$$('[data-profile-prefill]').forEach(b=>b.onclick=()=>{const key=decodeURIComponent(b.dataset.profilePrefill),v=db.profiles[key];$('#accountUsernameInput').value=`${v.classCode}-${v.studentId}`;$('#accountPasswordInput').value='';$('#accountPasswordInput').focus();});if(p&&!$('#accountUsernameInput').value)$('#accountUsernameInput').value=`${p.classCode}-${p.studentId}`;}
  $('#accountLoginBtn').onclick=()=>cloudStudentLogin();
  ['accountUsernameInput','accountPasswordInput'].forEach(id=>$('#'+id).addEventListener('keydown',e=>{if(e.key==='Enter')$('#accountLoginBtn').click();}));
  $('#logoutBtn').onclick=async()=>{try{await cloudClient?.auth.signOut()}catch(e){} cloudState.user=null;cloudState.role='';cloudState.mustChangePassword=false;cloudState.username='';logoutProfile();$('#firstPasswordBox')?.classList.add('cloud-hidden');$('#accountError').textContent='已退出当前学生。';refreshCloudUI();};

'''+s[end:]

start=s.index('  async function cloudStudentAuth(action){')
end=s.index('  async function refreshCloudUI(){',start)
s=s[:start]+r'''  async function cloudStudentLogin(){if(!cloudClient){cloudMsg('#accountError','云端组件未加载，请检查网络。');return}let username=$('#accountUsernameInput').value.trim().toUpperCase(),password=$('#accountPasswordInput').value;if(!username||!password){cloudMsg('#accountError','请输入老师发放的用户名和密码。');return}cloudMsg('#accountError','正在登录云端…');try{let r=await fetch(`${CLOUD_URL}/functions/v1/student-auth`,{method:'POST',headers:{'Content-Type':'application/json','apikey':CLOUD_KEY},body:JSON.stringify({action:'login',username,password})}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'云端登录失败');await cloudClient.auth.setSession({access_token:j.session.access_token,refresh_token:j.session.refresh_token});cloudState.user={id:j.user.id};cloudState.role='student';cloudState.classId=j.class.id;cloudState.className=j.class.name;cloudState.displayName=j.user.display_name||j.account.student_code;cloudState.mustChangePassword=!!j.account.must_change_password;cloudState.username=j.account.username||username;let join=j.class.join_code||username.split('-')[0],sid=j.account.student_code;localStorage.setItem('ratiobot_last_class',join);localStorage.setItem('ratiobot_last_student',sid);cloudMsg('#accountError',cloudState.mustChangePassword?'✓ 初始密码验证成功，请先设置自己的新密码。':'✓ 云端登录成功。','');await cloudLoadStudentData(join,sid);$('#accountPasswordInput').value='';renderAccount();renderGrowth();renderStats();refreshCloudUI();if(cloudState.mustChangePassword){$('#firstPasswordBox').classList.remove('cloud-hidden');$('#firstNewPassword').focus();go('account',{bypass:true});return}const next=cloudState.pendingPage||'growth';cloudState.pendingPage='';setTimeout(()=>go(next,{bypass:true}),250)}catch(e){cloudMsg('#accountError',e.message||'云端登录失败');beep(180,.1,'square')}}
  async function setFirstStudentPassword(){let a=$('#firstNewPassword').value,b=$('#firstNewPassword2').value;if(a!==b)return cloudMsg('#firstPasswordMsg','两次输入的密码不一致。','bad');if(!/^[A-Za-z0-9!@#$%^&*._-]{6,32}$/.test(a))return cloudMsg('#firstPasswordMsg','密码需为6–32位，可使用字母、数字及常见符号。','bad');let {data}=await cloudClient.auth.getSession(),token=data?.session?.access_token;if(!token)return cloudMsg('#firstPasswordMsg','登录状态已失效，请重新登录。','bad');cloudMsg('#firstPasswordMsg','正在保存新密码…');try{let r=await fetch(`${CLOUD_URL}/functions/v1/student-auth`,{method:'POST',headers:{'Content-Type':'application/json','apikey':CLOUD_KEY,'Authorization':`Bearer ${token}`},body:JSON.stringify({action:'change_password',new_password:a})}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'修改密码失败');cloudState.mustChangePassword=false;$('#firstNewPassword').value='';$('#firstNewPassword2').value='';$('#firstPasswordBox').classList.add('cloud-hidden');cloudMsg('#accountError','✓ 新密码已设置完成。','');refreshCloudUI();const next=cloudState.pendingPage||'growth';cloudState.pendingPage='';setTimeout(()=>go(next,{bypass:true}),250)}catch(e){cloudMsg('#firstPasswordMsg',e.message||'修改密码失败。','bad')}}
  $('#setFirstPasswordBtn').onclick=setFirstStudentPassword;
'''+s[end:]

start=s.index('  async function loadTeacherDashboard(classId){')
end=s.index('  async function initCloud(){',start)
s=s[:start]+r'''  function parseStudentCodes(text){text=String(text||'').trim();if(!text)return[];let m=text.match(/^\s*(\d+)\s*[-~—–]\s*(\d+)\s*$/);if(m){let a=Number(m[1]),b=Number(m[2]);if(a>b)[a,b]=[b,a];if(b-a>99)return[];return Array.from({length:b-a+1},(_,i)=>String(a+i))}return[...new Set(text.split(/[\s,，;；]+/).map(x=>x.trim()).filter(Boolean))].slice(0,100)}
  let lastCredentialText='';
  async function teacherApi(payload){let {data}=await cloudClient.auth.getSession(),token=data?.session?.access_token;if(!token)throw new Error('教师登录状态已失效，请重新登录。');let r=await fetch(`${CLOUD_URL}/functions/v1/student-auth`,{method:'POST',headers:{'Content-Type':'application/json','apikey':CLOUD_KEY,'Authorization':`Bearer ${token}`},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'操作失败');return j}
  async function bulkCreateStudents(){let classId=$('#teacherClassSelect').value,codes=parseStudentCodes($('#bulkStudentCodes').value);if(!classId)return cloudMsg('#teacherProvisionMsg','请先选择班级。','bad');if(!codes.length)return cloudMsg('#teacherProvisionMsg','请输入学号，例如 1-45。','bad');cloudMsg('#teacherProvisionMsg',`正在创建 ${codes.length} 个学生账号…`);try{let j=await teacherApi({action:'teacher_bulk_create',class_id:classId,student_codes:codes}),rows=j.created||[];lastCredentialText=['用户名\t初始密码',...rows.map(x=>`${x.username}\t${x.temporary_password}`)].join('\n');$('#teacherCredentials').innerHTML=rows.length?`<div class="teacher-row head"><span>用户名</span><span>初始密码</span><span>学号</span><span>状态</span><span>说明</span></div>`+rows.map(x=>`<div class="teacher-row"><span><b>${x.username}</b></span><span><b>${x.temporary_password}</b></span><span>${x.student_code}</span><span>未激活</span><span>首次登录后必须改密</span></div>`).join(''):'<div class="empty">没有新建账号；这些学号可能已经存在。</div>';cloudMsg('#teacherProvisionMsg',`✓ 新建 ${rows.length} 个，已存在 ${(j.skipped||[]).length} 个，失败 ${(j.failed||[]).length} 个。请立即复制本次初始密码表。`,'good');await loadTeacherDashboard(classId)}catch(e){cloudMsg('#teacherProvisionMsg',e.message||'批量创建失败。','bad')}}
  async function resetStudentPassword(classId,studentCode){if(!confirm(`为 ${studentCode} 号重置密码？原密码将立即失效。`))return;try{let j=await teacherApi({action:'teacher_reset_password',class_id:classId,student_code:studentCode});lastCredentialText=`用户名\t临时密码\n${j.username}\t${j.temporary_password}`;$('#teacherCredentials').innerHTML=`<div class="teacher-row head"><span>用户名</span><span>新临时密码</span><span>学号</span><span>状态</span><span>说明</span></div><div class="teacher-row"><span><b>${j.username}</b></span><span><b>${j.temporary_password}</b></span><span>${studentCode}</span><span>待重新改密</span><span>此密码仅本次显示</span></div>`;cloudMsg('#teacherProvisionMsg','✓ 已重置。请把新的临时密码单独发给学生。','good');await loadTeacherDashboard(classId)}catch(e){cloudMsg('#teacherProvisionMsg',e.message||'重置失败。','bad')}}
  async function loadTeacherDashboard(classId){if(!classId)return;let {data:accounts,error}=await cloudClient.from('student_accounts').select('user_id,student_code,login_name,must_change_password,activated_at,password_reset_at').eq('class_id',classId).order('student_code');if(error)return cloudMsg('#teacherMsg',error.message,'bad');let ids=(accounts||[]).map(x=>x.user_id),profiles=[];if(ids.length){let r=await cloudClient.from('profiles').select('*').in('user_id',ids);profiles=r.data||[]}let pm=Object.fromEntries(profiles.map(x=>[x.user_id,x]));$('#teacherTable').innerHTML=`<div class="teacher-row head"><span>学生账号</span><span>状态</span><span>等级</span><span>R积分</span><span>密码</span></div>`+(accounts||[]).map(a=>{let x=pm[a.user_id]||{},status=a.must_change_password?'未完成首次改密':'已激活';return `<div class="teacher-row"><span><b>${a.login_name||a.student_code}</b><br><small>${x.display_name||a.student_code}</small></span><span>${status}</span><span>Lv.${x.level||1}<br>BASE ${x.base_level||0}</span><span>${x.r_points||0}</span><span><button class="ghost small" data-reset-student="${a.student_code}">重置临时密码</button></span></div>`}).join('')+((accounts||[]).length?'':'<div class="empty">这个班还没有学生账号，请在上方统一创建。</div>');$$('[data-reset-student]').forEach(b=>b.onclick=()=>resetStudentPassword(classId,b.dataset.resetStudent))}
  function exportLocalBackup(){const payload={format:'ratiobot-local-backup-v1',exportedAt:new Date().toISOString(),studentDB:loadDB(),legacyStats:(()=>{try{return JSON.parse(localStorage.getItem(LEGACY_STORAGE_KEY)||'null')}catch(e){return null}})()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`RATIOBOT_本机备份_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  async function importLegacyBackup(){const file=$('#legacyImportFile')?.files?.[0];if(!file)return cloudMsg('#cloudMigrationMsg','请先选择旧版 JSON 备份文件。','bad');try{const j=JSON.parse(await file.text());let incoming=j.studentDB||j.db||j;let profiles=incoming?.profiles||{};if(j.legacyStats&&!Object.keys(profiles).length){localStorage.setItem(LEGACY_STORAGE_KEY,JSON.stringify(j.legacyStats));const db=loadDB();db.migratedV7=false;saveDB(db);migrateLegacy();profiles=loadDB().profiles||{}}if(!profiles||!Object.keys(profiles).length)throw new Error('备份中没有可识别的学生进度');const db=loadDB();for(const [k,p] of Object.entries(profiles)){const ep=ensureProfileShape(p);if(ep)db.profiles[k]=db.profiles[k]?mergeProfilesForMigration(db.profiles[k],ep,ep.classCode,ep.studentId):ep;}saveDB(db);renderAccount();cloudMsg('#cloudMigrationMsg',`✓ 已导入 ${Object.keys(profiles).length} 个本机档案。请用对应学生账号云端登录，系统会继续合并同步。`,'good')}catch(e){cloudMsg('#cloudMigrationMsg',e.message||'旧版备份导入失败。','bad')}}
  $('#bulkCreateStudentsBtn').onclick=bulkCreateStudents;$('#copyCredentialsBtn').onclick=async()=>{if(!lastCredentialText)return cloudMsg('#teacherProvisionMsg','当前没有可复制的初始密码表。','bad');try{await navigator.clipboard.writeText(lastCredentialText);cloudMsg('#teacherProvisionMsg','✓ 已复制本次账号表。','good')}catch(e){cloudMsg('#teacherProvisionMsg','复制失败，请手动复制上方表格。','bad')}};
  $('#legacyImportBtn').onclick=importLegacyBackup;$('#localBackupBtn').onclick=exportLocalBackup;
  $('#teacherSignupBtn').onclick=()=>teacherAuth('signup');$('#teacherLoginBtn').onclick=()=>teacherAuth('login');$('#teacherLogoutBtn').onclick=async()=>{await cloudClient?.auth.signOut();cloudState.user=null;cloudState.role='';cloudState.mustChangePassword=false;cloudState.username='';$('#teacherDashboard').classList.add('cloud-hidden');$('#teacherCreateBox').classList.add('cloud-hidden');cloudMsg('#teacherMsg','已退出教师账号。');refreshCloudUI()};$('#createClassBtn').onclick=createTeacherClass;$('#teacherClassSelect').onchange=e=>{cloudState.classId=e.target.value;loadTeacherDashboard(e.target.value)};$('#refreshClassWallBtn').onclick=()=>cloudState.role==='student'?loadStudentClassWall():loadTeacherClasses();
'''+s[end:]

old="""else if(cloudState.role==='student'){let {data:m}=await cloudClient.from('class_members').select('class_id,student_code,classes(name,join_code)').eq('user_id',sess.user.id).eq('role','student').maybeSingle();if(m){cloudState.classId=m.class_id;cloudState.className=m.classes?.name||'';let cls=m.classes?.join_code||localStorage.getItem('ratiobot_last_class')||'',sid=m.student_code||localStorage.getItem('ratiobot_last_student')||'';let {data:pr}=await cloudClient.from('profiles').select('display_name').eq('user_id',sess.user.id).maybeSingle();cloudState.displayName=pr?.display_name||sid;await cloudLoadStudentData(cls,sid)}}refreshCloudUI()}"""
new="""else if(cloudState.role==='student'){let {data:m}=await cloudClient.from('class_members').select('class_id,student_code,classes(name,join_code)').eq('user_id',sess.user.id).eq('role','student').maybeSingle();if(m){cloudState.classId=m.class_id;cloudState.className=m.classes?.name||'';let cls=m.classes?.join_code||localStorage.getItem('ratiobot_last_class')||'',sid=m.student_code||localStorage.getItem('ratiobot_last_student')||'';let {data:pr}=await cloudClient.from('profiles').select('display_name').eq('user_id',sess.user.id).maybeSingle();let {data:acct}=await cloudClient.from('student_accounts').select('login_name,must_change_password').eq('user_id',sess.user.id).maybeSingle();cloudState.displayName=pr?.display_name||sid;cloudState.username=acct?.login_name||`${cls}-${sid}`;cloudState.mustChangePassword=!!acct?.must_change_password;$('#accountUsernameInput').value=cloudState.username;await cloudLoadStudentData(cls,sid);if(cloudState.mustChangePassword){$('#firstPasswordBox').classList.remove('cloud-hidden');go('account',{bypass:true})}}}refreshCloudUI()}"""
must_replace(old,new,'init cloud student state')
s=s.replace("`${cloudState.className||state.classCode} · ${cloudState.displayName||state.studentId}`","`${cloudState.username||cloudState.className||state.classCode}${cloudState.mustChangePassword?' · 待设置密码':''}`",1)

for stale in ['cloudRegisterBtn','localLoginBtn','accountClassInput','accountStudentInput','accountPinInput','accountNameInput']:
    if stale in s: raise SystemExit(f'stale student auth control remains: {stale}')

p.write_text(s,'utf-8')
print('Teacher-provisioned account model applied')
