from pathlib import Path
import re,sys
root=Path(sys.argv[1] if len(sys.argv)>1 else '_site')
ip=root/'index.html'; rp=root/'rings.html'
s=ip.read_text('utf-8'); r=rp.read_text('utf-8')
MARK='rings-stats-xp-balance-v2'
if MARK not in s:
    s=s.replace("function levelInfo(totalXP){let level=1,spent=0,need=120;while(level<120&&totalXP>=spent+need){spent+=need;level++;need=120+(level-1)*60;}","function levelInfo(totalXP){let level=1,spent=0,need=300;while(level<120&&totalXP>=spent+need){spent+=need;level++;need=300+(level-1)*150;} /* rings-stats-xp-balance-v2 */",1)
    old="window.addEventListener('message',ev=>{let d=ev.data;if(!d||d.type!=='ratiobot-game-clear')return;let frame=$('#ringsFrame');if(frame&&ev.source!==frame.contentWindow)return;if(d.mode==='duel'||d.playMode==='duel'){try{ev.source.postMessage({type:'ratiobot-score-result',gain:0,balance:Number(currentProfile()?.economy?.credits||0),message:'PK 模式不计 R积分'},'*')}catch(e){}return;}let p=currentProfile();if(!p){try{ev.source.postMessage({type:'ratiobot-score-result',gain:0,balance:0,message:'未登录学生账号，本局未计分'},'*')}catch(e){}return;}let res=recordGameClear(p,'rings',String(d.signature||'random-rules'),!!d.challenge,'normal','rings','integer');p.economy.modules.numberRings.clears++;saveCurrentProfile(p);renderGrowth();renderStats();let balance=Number(p.economy?.credits||0);try{ev.source.postMessage({type:'ratiobot-score-result',gain:res.gain,balance,points:res.points,message:res.gain?`总部计分 +${res.gain} R积分 · 当前余额 ${balance}`:`本局 0 分：${res.reason}`},'*')}catch(e){}});"
    new="""window.ratiobotRecordRingsClear=function(d={}){let p=currentProfile();if(d.mode==='duel'||d.playMode==='duel')return {gain:0,balance:Number(p?.economy?.credits||0),message:'PK 模式不计 R积分'};if(!p)return {gain:0,balance:0,message:'未登录学生账号，本局未计分'};let res=recordGameClear(p,'rings',String(d.signature||('rings-'+Date.now())),!!d.challenge,'normal','rings','integer');p.economy.modules.numberRings.clears++;p.games=Number(p.games||0)+1;const td=todayKey();if(!p.activeDates.includes(td))p.activeDates.push(td);p.activeDates=p.activeDates.slice(-60);let grade=String(d.grade||'完成'),ops=Number(d.totalOps||0),fails=Number(d.totalFails||0),li=levelInfo(p.xp);p.history.unshift({game:'rings',at:new Date().toISOString(),classCode:p.classCode,studentId:p.studentId,stage:'rings',numberType:'classification',difficulty:'normal',accuracy:null,totalOps:ops,totalFails:fails,grade,xp:0,rGain:res.gain,level:li.level});p.history=p.history.slice(0,10);saveCurrentProfile(p);renderGrowth();renderStats();let balance=Number(p.economy?.credits||0);return {gain:res.gain,balance,points:res.points,message:res.gain?`总部计分 +${res.gain} R积分 · 当前余额 ${balance}`:`本局 0 分：${res.reason}`};};
window.addEventListener('message',ev=>{let d=ev.data;if(!d||d.type!=='ratiobot-game-clear')return;let frame=$('#ringsFrame');if(frame&&ev.source!==frame.contentWindow)return;let out=window.ratiobotRecordRingsClear(d);try{ev.source.postMessage({type:'ratiobot-score-result',...out},'*')}catch(e){}});"""
    if old not in s: raise SystemExit('parent rings listener not found')
    s=s.replace(old,new,1)
    oldhist="const h=(p.history||[]).slice(0,10);$('#historyCount').textContent=h.length?`已保存 ${h.length} / 10 次`:'最多保留 10 次';$('#historyList').innerHTML=h.length?h.map((r,i)=>{const stage=E.STAGES[r.stage]?.label||r.stage,nt=r.stage==='power'?'乘方底数规则':(E.NUMBER_TYPES[r.numberType]?.label||r.numberType),diff=E.DIFFICULTY[r.difficulty]?.label||r.difficulty;const bracket=E.STAGES[r.stage]?.allowBrackets?` · 括号${r.brackets==='auto'?'自动':r.brackets+'对'}`:'';return `<div class=\"history-item\"><div class=\"history-item-head\"><div class=\"history-student\">${p.classCode}<br>学号 ${p.studentId}</div><div class=\"history-main\"><b>${stage} · ${nt}</b><span>${diff}${bracket}</span></div><div class=\"history-result\"><b>${r.accuracy}%</b><span>首次正确率</span></div></div><div class=\"history-extra\"><div><small>本局成长</small><b>+${r.xp||0} XP</b></div><div><small>最高连击</small><b>${r.bestCombo}</b></div><div><small>平均用时</small><b>${Number(r.avgTime||0).toFixed(1)} s</b></div></div><div class=\"history-time\">${displayDate(r.at)} · 完成后 Lv.${r.level||'?'} · 最近第 ${i+1} 条</div></div>`;}).join(''):'<div class=\"empty\">还没有详细训练记录。完成一局后会保存类型、难度、结果和获得的 XP。</div>';"
    newhist="""const h=(p.history||[]).slice(0,10);$('#historyCount').textContent=h.length?`已保存 ${h.length} / 10 次`:'最多保留 10 次';$('#historyList').innerHTML=h.length?h.map((r,i)=>{if(r.game==='rings'){return `<div class=\"history-item\"><div class=\"history-item-head\"><div class=\"history-student\">${p.classCode}<br>学号 ${p.studentId}</div><div class=\"history-main\"><b>数圈侦探 · 分类推理</b><span>单人完整挑战</span></div><div class=\"history-result\"><b>${r.grade||'完成'}</b><span>策略评级</span></div></div><div class=\"history-extra\"><div><small>本局积分</small><b>+${r.rGain||0} R</b></div><div><small>总操作</small><b>${r.totalOps||0} 次</b></div><div><small>失败投放</small><b>${r.totalFails||0} 次</b></div></div><div class=\"history-time\">${displayDate(r.at)} · 完成后 Lv.${r.level||'?'} · 最近第 ${i+1} 条</div></div>`;}const stage=E.STAGES[r.stage]?.label||r.stage,nt=r.stage==='power'?'乘方底数规则':(E.NUMBER_TYPES[r.numberType]?.label||r.numberType),diff=E.DIFFICULTY[r.difficulty]?.label||r.difficulty;const bracket=E.STAGES[r.stage]?.allowBrackets?` · 括号${r.brackets==='auto'?'自动':r.brackets+'对'}`:'';return `<div class=\"history-item\"><div class=\"history-item-head\"><div class=\"history-student\">${p.classCode}<br>学号 ${p.studentId}</div><div class=\"history-main\"><b>${stage} · ${nt}</b><span>${diff}${bracket}</span></div><div class=\"history-result\"><b>${r.accuracy}%</b><span>首次正确率</span></div></div><div class=\"history-extra\"><div><small>本局成长</small><b>+${r.xp||0} XP</b></div><div><small>最高连击</small><b>${r.bestCombo}</b></div><div><small>平均用时</small><b>${Number(r.avgTime||0).toFixed(1)} s</b></div></div><div class=\"history-time\">${displayDate(r.at)} · 完成后 Lv.${r.level||'?'} · 最近第 ${i+1} 条</div></div>`;}).join(''):'<div class=\"empty\">还没有详细训练记录。完成一局后会保存训练结果。</div>';"""
    if oldhist not in s: raise SystemExit('history renderer not found')
    s=s.replace(oldhist,newhist,1)
    ip.write_text(s,'utf-8')

if 'rings-direct-score-v2' not in r:
    old="if(playMode==='solo'&&!window.__hqScoreSent){window.__hqScoreSent=true;try{parent.postMessage({type:'ratiobot-game-clear',game:'rings',signature:rounds.map(r=>r.aRule+'>'+r.bRule).join('|'),challenge:(totalFails<=3&&totalOps<=16)},'*')}catch(e){}}"
    new="""if(playMode==='solo'&&!window.__hqScoreSent){window.__hqScoreSent=true;let payload={type:'ratiobot-game-clear',game:'rings',signature:rounds.map(x=>x.aRule+'>'+x.bRule).join('|'),challenge:(totalFails<=3&&totalOps<=16),totalOps,totalFails,grade:(totalOps<=14?'S · 很会选线索':totalOps<=19?'A · 推理很稳':totalOps<=25?'B · 已掌握':'继续优化策略')};try{if(parent&&typeof parent.ratiobotRecordRingsClear==='function'){let out=parent.ratiobotRecordRingsClear(payload);sessionRPoints=Number(out?.gain||0);setTimeout(()=>window.dispatchEvent(new MessageEvent('message',{data:{type:'ratiobot-score-result',...out}})),0);}else parent.postMessage(payload,'*')}catch(e){try{parent.postMessage(payload,'*')}catch(_){}}} /* rings-direct-score-v2 */"""
    if old not in r: raise SystemExit('child rings send block not found')
    r=r.replace(old,new,1)
    rp.write_text(r,'utf-8')
print('rings stats + direct score + slower XP applied')
