from pathlib import Path
import re,sys,subprocess,tempfile
root=Path(sys.argv[1] if len(sys.argv)>1 else '_site')
index=root/'index.html'; rings=root/'rings.html'
s=index.read_text('utf-8')
MARK='progress-balance-fix-v2'
if MARK not in s:
    s=s.replace('</style>', '\n/* progress-balance-fix-v2 */\n</style>', 1)
    pat=r"function levelInfo\(totalXP\)\{let level=1,spent=0,need=120;while\(level<120&&totalXP>=spent\+need\)\{spent\+=need;level\+\+;need=120\+\(level-1\)\*60;\}if\(level>=120\)\{return \{level:120,into:0,need:0,pct:100,toNext:0,capped:true,spent\};\}const into=Math.max\(0,totalXP-spent\),pct=Math.max\(0,Math.min\(100,Math.round\(into/need\*100\)\)\);return \{level,into,need,pct,toNext:Math.max\(0,need-into\),capped:false,spent\};\}"
    repl="function levelInfo(totalXP){let level=1,spent=0,need=260;while(level<120&&totalXP>=spent+need){spent+=need;level++;need=260+(level-1)*85;}if(level>=120){return {level:120,into:0,need:0,pct:100,toNext:0,capped:true,spent};}const into=Math.max(0,totalXP-spent),pct=Math.max(0,Math.min(100,Math.round(into/need*100)));return {level,into,need,pct,toNext:Math.max(0,need-into),capped:false,spent};}"
    s,n=re.subn(pat,repl,s,count=1)
    if n!=1: raise SystemExit('levelInfo target not found')
    old="function calcQuestionXP(q,first,hints){const dm={easy:1,normal:1.3,hard:1.6}[q.difficulty]||1;const nm={integer:1,intdec:1.1,intfrac:1.2,fracdec:1.3}[q.numberType]||1;const sm={add:1,addsub:1.05,mul:1,muldiv:1.08,mixed:1.18,power:1.15,supermixed:1.32}[q.stage]||1;const perf=first?1:.6,hint=hints>0?.78:1;return Math.max(2,Math.round(10*dm*nm*sm*perf*hint));}"
    new="function calcQuestionXP(q,first,hints){const dm={easy:1,normal:1.3,hard:1.6}[q.difficulty]||1;const nm={integer:1,intdec:1.1,intfrac:1.2,fracdec:1.3}[q.numberType]||1;const sm={add:1,addsub:1.05,mul:1,muldiv:1.08,mixed:1.18,power:1.15,supermixed:1.32}[q.stage]||1;const perf=first?1:.6,hint=hints>0?.78:1;return Math.max(2,Math.round(8*dm*nm*sm*perf*hint));}"
    if old not in s: raise SystemExit('calcQuestionXP target not found')
    s=s.replace(old,new,1)
    s=re.sub(r"function ensureRingsLoaded\(force=false\)\{let f=\$\('#ringsFrame'\);if\(!f\)return;if\(force\|\|!f\.dataset\.loaded\)\{.*?f\.dataset\.loaded='1';\}\}","function ensureRingsLoaded(force=false){let f=$('#ringsFrame');if(!f)return;if(force||!f.dataset.loaded){f.removeAttribute('srcdoc');f.src='rings.html?v=46';f.dataset.loaded='1';}}",s,count=1,flags=re.S)
    msg_pat=r"window\.addEventListener\('message',ev=>\{let d=ev\.data;if\(!d\|\|d\.type!=='ratiobot-game-clear'\)return;.*?\}\);"
    m=re.search(msg_pat,s,flags=re.S)
    if not m: raise SystemExit('rings parent listener target not found')
    parent_code="""function ratiobotAwardRings(d={}){\n    if(d.mode==='duel'||d.playMode==='duel')return {type:'ratiobot-score-result',gain:0,balance:Number(currentProfile()?.economy?.credits||0),message:'PK 模式不计 R积分'};\n    let p=currentProfile();\n    if(!p)return {type:'ratiobot-score-result',gain:0,balance:0,message:'未登录学生账号，本局未计分'};\n    let res=recordGameClear(p,'rings',String(d.signature||'rings-'+Date.now()),!!d.challenge,'normal','rings','integer');\n    p.economy.modules.numberRings.clears++;\n    const ops=Math.max(0,Number(d.totalOps||d.ops||0)),fails=Math.max(0,Number(d.totalFails||d.fails||0));\n    const acc=ops?Math.max(0,Math.min(100,Math.round((ops-fails)/ops*100))):100;\n    const grade=String(d.grade|| (ops<=14?'S · 很会选线索':ops<=19?'A · 推理很稳':ops<=25?'B · 已掌握':'继续优化策略'));\n    p.history ||= [];\n    p.history.unshift({at:new Date().toISOString(),classCode:p.classCode,studentId:p.studentId,game:'rings',stage:'rings',numberType:'classification',difficulty:'normal',brackets:'0',accuracy:acc,bestCombo:0,avgTime:null,xp:0,level:levelInfo(p.xp).level,totalOps:ops,totalFails:fails,grade});\n    p.history=p.history.slice(0,10);\n    saveCurrentProfile(p);renderGrowth();renderStats();\n    const balance=Number(p.economy?.credits||0);\n    return {type:'ratiobot-score-result',gain:res.gain,balance,points:res.points,message:res.gain?`数圈侦探通关 +${res.gain} R积分 · 当前余额 ${balance}`:`本局 0 分：${res.reason}`};\n  }\n  window.ratiobotAwardRings=ratiobotAwardRings;\n  window.addEventListener('message',ev=>{let d=ev.data;if(!d||d.type!=='ratiobot-game-clear')return;let frame=$('#ringsFrame');if(frame&&ev.source!==frame.contentWindow)return;let result=ratiobotAwardRings(d);try{ev.source.postMessage(result,'*')}catch(e){}});"""
    s=s[:m.start()]+parent_code+s[m.end():]
    old="const h=(p.history||[]).slice(0,10);$('#historyCount').textContent=h.length?`已保存 ${h.length} / 10 次`:'最多保留 10 次';$('#historyList').innerHTML=h.length?h.map((r,i)=>{const stage=E.STAGES[r.stage]?.label||r.stage,nt=r.stage==='power'?'乘方底数规则':(E.NUMBER_TYPES[r.numberType]?.label||r.numberType),diff=E.DIFFICULTY[r.difficulty]?.label||r.difficulty;const bracket=E.STAGES[r.stage]?.allowBrackets?` · 括号${r.brackets==='auto'?'自动':r.brackets+'对'}`:'';return `<div class=\"history-item\"><div class=\"history-item-head\"><div class=\"history-student\">${p.classCode}<br>学号 ${p.studentId}</div><div class=\"history-main\"><b>${stage} · ${nt}</b><span>${diff}${bracket}</span></div><div class=\"history-result\"><b>${r.accuracy}%</b><span>首次正确率</span></div></div><div class=\"history-extra\"><div><small>本局成长</small><b>+${r.xp||0} XP</b></div><div><small>最高连击</small><b>${r.bestCombo}</b></div><div><small>平均用时</small><b>${Number(r.avgTime||0).toFixed(1)} s</b></div></div><div class=\"history-time\">${displayDate(r.at)} · 完成后 Lv.${r.level||'?'} · 最近第 ${i+1} 条</div></div>`;}).join(''):'<div class=\"empty\">还没有详细训练记录。完成一局后会保存类型、难度、结果和获得的 XP。</div>';"
    new="const h=(p.history||[]).slice(0,10);$('#historyCount').textContent=h.length?`已保存 ${h.length} / 10 次`:'最多保留 10 次';$('#historyList').innerHTML=h.length?h.map((r,i)=>{const isRings=r.stage==='rings'||r.game==='rings',stage=isRings?'数圈侦探':(E.STAGES[r.stage]?.label||r.stage),nt=isRings?'分类推理':(r.stage==='power'?'乘方底数规则':(E.NUMBER_TYPES[r.numberType]?.label||r.numberType)),diff=isRings?'单人闯关':(E.DIFFICULTY[r.difficulty]?.label||r.difficulty);const bracket=!isRings&&E.STAGES[r.stage]?.allowBrackets?` · 括号${r.brackets==='auto'?'自动':r.brackets+'对'}`:'';const extra=isRings?`<div><small>总操作</small><b>${r.totalOps||0}</b></div><div><small>失败投放</small><b>${r.totalFails||0}</b></div><div><small>策略评级</small><b>${r.grade||'—'}</b></div>`:`<div><small>本局成长</small><b>+${r.xp||0} XP</b></div><div><small>最高连击</small><b>${r.bestCombo}</b></div><div><small>平均用时</small><b>${Number(r.avgTime||0).toFixed(1)} s</b></div>`;return `<div class=\"history-item\"><div class=\"history-item-head\"><div class=\"history-student\">${p.classCode}<br>学号 ${p.studentId}</div><div class=\"history-main\"><b>${stage} · ${nt}</b><span>${diff}${bracket}</span></div><div class=\"history-result\"><b>${r.accuracy}%</b><span>${isRings?'投放准确率':'首次正确率'}</span></div></div><div class=\"history-extra\">${extra}</div><div class=\"history-time\">${displayDate(r.at)} · 完成后 Lv.${r.level||'?'} · 最近第 ${i+1} 条</div></div>`;}).join(''):'<div class=\"empty\">还没有详细训练记录。完成运算或数圈侦探后都会保存记录。</div>';"
    if old not in s: raise SystemExit('renderStats history target not found')
    s=s.replace(old,new,1)
    index.write_text(s,'utf-8')
r=rings.read_text('utf-8')
if 'rings-direct-score-v2' not in r:
    old="if(playMode==='solo'&&!window.__hqScoreSent){window.__hqScoreSent=true;try{parent.postMessage({type:'ratiobot-game-clear',game:'rings',signature:rounds.map(r=>r.aRule+'>'+r.bRule).join('|'),challenge:(totalFails<=3&&totalOps<=16)},'*')}catch(e){}}"
    new="if(playMode==='solo'&&!window.__hqScoreSent){window.__hqScoreSent=true;const payload={type:'ratiobot-game-clear',game:'rings',mode:'solo',playMode:'solo',signature:rounds.map(r=>r.aRule+'>'+r.bRule).join('|'),challenge:(totalFails<=3&&totalOps<=16),totalOps,totalFails,grade:(totalOps<=14?'S · 很会选线索':totalOps<=19?'A · 推理很稳':totalOps<=25?'B · 已掌握':'继续优化策略')};try{if(parent&&parent!==window&&typeof parent.ratiobotAwardRings==='function'){const res=parent.ratiobotAwardRings(payload);setTimeout(()=>window.postMessage(res,'*'),0)}else{parent.postMessage(payload,'*')}}catch(e){try{parent.postMessage(payload,'*')}catch(_){}}} /* rings-direct-score-v2 */"
    if old not in r: raise SystemExit('rings finish parent scoring target not found')
    r=r.replace(old,new,1)
    rings.write_text(r,'utf-8')
for page in (index,rings):
    txt=page.read_text('utf-8')
    scripts=re.findall(r'<script(?:[^>]*)>(.*?)</script>',txt,flags=re.S|re.I)
    with tempfile.TemporaryDirectory() as td:
        for i,js in enumerate(scripts):
            if not js.strip(): continue
            f=Path(td)/f's{i}.js';f.write_text(js,'utf-8')
            subprocess.run(['node','--check',str(f)],check=True,stdout=subprocess.DEVNULL)
print('progress/rings/stat patch applied')