const assert=require('node:assert/strict');
const fs=require('node:fs'), vm=require('node:vm');
const {JSDOM}=require('jsdom');
const root=process.env.SITE_DIR||'_site';
const html=fs.readFileSync(root+'/index.html','utf8');
const failures=[],writes=[];let failTable='';
const fixture={};
const client={auth:{onAuthStateChange(){},getSession:async()=>({data:{session:null}}),signOut:async()=>({error:null})},from(table){let data=[];const q={select(){data=fixture[table]||[];return q},eq(){return q},in(){return q},gte(){return q},order(){return q},maybeSingle:async()=>({data:null}),update(row){fixture[table]=(fixture[table]||[]).map(x=>({...x,...row}));return q},upsert(row){q.row=row;return q},throwOnError:async()=>{if(failTable===table)throw Error('simulated rejected write');writes.push({table,row:structuredClone(q.row)});return {error:null}},then(resolve){return Promise.resolve({data,error:null}).then(resolve)}};return q}};
const dom=new JSDOM(html,{url:'https://test.invalid/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;
w.structuredClone=structuredClone;w.supabase={createClient:()=>client};w.scrollTo=()=>{};w.Element.prototype.animate=()=>({});w.alert=()=>{};w.confirm=()=>true;w.console.warn=()=>{};
for(const script of w.document.scripts){if(script.src&&!/(review-(engine|ui)|daily)\.js$/.test(script.src))continue;let code=script.src?fs.readFileSync(root+'/'+new URL(script.src).pathname.split('/').pop(),'utf8'):script.textContent;new vm.Script(code);code=code.replace('    migrateLegacy();const initP=',`    window.__test={levelInfo,honorInfoFromProfile,cloudLevelBase,blankProfile,saveCurrentProfile,currentProfile,currentProfileKey,cloudState,cloudSyncProfile,renderGrowth,renderStats,go,openStudentGate,loadTeacherDashboard,teacherSwitchTab,rosterNameMap,loadStudentClassWall,peerState,ensureTodayRecord,calcQuestionXP};\n    migrateLegacy();const initP=`);w.eval(code)}
const t=w.__test;assert.ok(t,'main closure reaches initialization');
function student(){t.cloudState.user={id:'fixture-student'};t.cloudState.role='student';t.cloudState.mustChangePassword=false;t.saveCurrentProfile(t.blankProfile('TEST','1',''));}
function xpAt(lv){let n=0;for(let i=1;i<lv;i++)n+=260+(i-1)*85;return n;}
(async()=>{
 student();
 for(let lv=1;lv<=90;lv++){const p=t.currentProfile();p.xp=xpAt(lv);t.saveCurrentProfile(p);t.renderGrowth();const h=t.honorInfoFromProfile(p);assert.equal(h.currentBase,Math.floor((lv-1)/9)+1);assert.equal(h.phase,(lv-1)%9+1);assert.equal(t.cloudLevelBase(p).base,h.currentBase);assert.equal(w.document.querySelectorAll('#baseStageGallery article').length,9);assert.equal(w.document.querySelectorAll('#baseCompleteGallery article').length,Math.min(3,Math.floor(lv/9)));assert.equal(w.document.querySelector('#growthLevel').textContent,String(h.phase));assert.ok(!/BASE\s*0\b/.test(w.document.body.textContent));}
 assert.equal(t.levelInfo(259).level,1);assert.equal(t.levelInfo(260).level,2);assert.equal(t.levelInfo(xpAt(90)+999999).level,90);
 for(const [id,target] of [['homeGrowthBtn','growth'],['homeStatsBtn','stats'],['playerBtn','account'],['growthSwitchBtn','account'],['statsSwitchBtn','account']]){t.go('home');w.document.getElementById(id).click();assert.ok(w.document.getElementById(target).classList.contains('active'),id+' click routes to '+target);}
 console.log('PASS 90 levels, BASE boundaries, retained completed collections and slow XP');
 for(const [mistakes,gain] of [[0,8],[1,4],[2,0]]){student();const payload={profileKey:t.currentProfileKey(),runId:'run-'+mistakes,mode:'solo',abMistakes:mistakes,totalOps:20,totalFails:2,roundCount:3,grade:'A · 推理很稳',durationSeconds:120};const r=w.ratiobotAwardRingsV53(payload);const p=t.currentProfile();assert.equal(r.gain,gain);assert.equal(p.economy.credits,gain);assert.equal(p.history.length,1);assert.equal(p.history[0].rGain,gain);assert.equal(p.history[0].accuracy,90);assert.equal(p.history[0].durationSeconds,120);assert.equal(p.history[0].abMistakes,mistakes);assert.match(w.document.querySelector('#historyList').textContent,/数圈侦探 · 分类推理/);assert.match(w.document.querySelector('#historyList').textContent,/120 s/);assert.equal(w.ratiobotAwardRingsV53(payload).gain,gain);assert.equal(t.currentProfile().history.length,1);await t.cloudSyncProfile();const pr=writes.filter(x=>x.table==='profiles').at(-1).row,snap=writes.filter(x=>x.table==='progress_snapshots').at(-1).row;assert.equal(pr.r_points,gain);assert.equal(Object.hasOwn(pr,'display_name'),false,'progress sync must not overwrite corrected roster names');assert.equal(snap.economy.credits,gain);assert.equal(snap.game_stats.history[0].rGain,gain);assert.equal(t.currentProfile().pendingCloud,false);}
 console.log('PASS 8/4/0: settlement, wallet, detailed record, snapshot payload, duplicate idempotency');
 student();failTable='progress_snapshots';w.ratiobotAwardRingsV53({profileKey:t.currentProfileKey(),runId:'failed-sync',totalOps:10,roundCount:3});assert.equal(await t.cloudSyncProfile(),false);assert.equal(t.currentProfile().pendingCloud,true);assert.equal(t.currentProfile().economy.credits,8);failTable='';assert.equal(await t.cloudSyncProfile(),true);assert.equal(t.currentProfile().pendingCloud,false);
 assert.equal(w.ratiobotAwardRingsV53({profileKey:'other-student',runId:'wrong'}).error,true);assert.equal(t.currentProfile().economy.credits,8);
 console.log('PASS cloud error remains pending, retry succeeds, changed student rejected');
 student();t.renderGrowth();assert.equal(w.document.querySelectorAll('#unifiedBadgeGrid article').length,16);assert.equal(w.document.querySelectorAll('#unifiedBadgeGrid img').length,16);
 for(const id of ['rules','train','rings']){t.go(id);assert.ok(w.document.getElementById(id).classList.contains('active'),id+' route active');}
 t.openStudentGate();assert.ok(w.document.querySelector('#studentView').classList.contains('hidden'));assert.ok(!w.document.querySelector('#gameView').classList.contains('hidden'));
 console.log('PASS 16 badge image elements, A/B/C routes, logged-in training skips password');
 t.cloudState.classId='fixture-class';
 fixture.class_public_cards=[{user_id:'peer-2',student_code:'2',display_name:'<img src=x onerror=alert(1)>',level:10,streak:3,today_checked_in:true,today_points:20,public_training:{badges:['first_round'],history:[{game:'rings',at:new Date().toISOString(),accuracy:90,rGain:4,abMistakes:1,totalOps:20,totalFails:2,durationSeconds:120,grade:'A'}]}},{user_id:'peer-1',student_code:'1',display_name:'1号',level:1,today_points:0,public_training:{history:[{game:'rings',at:new Date().toISOString(),rGain:0}]}}];
 const beforePeer=JSON.stringify(t.currentProfile());await t.loadStudentClassWall();
 assert.equal(w.document.querySelectorAll('[data-peer]').length,2);assert.equal(w.document.querySelector('[data-peer]').dataset.peer,'peer-1');
 assert.equal(w.document.querySelector('[data-peer="peer-1"]').classList.contains('training'),true);
 assert.equal(w.document.querySelectorAll('#peerGrid img[onerror]').length,0);
 w.document.querySelector('[data-peer="peer-2"]').click();assert.equal(w.document.querySelector('#peerDetail').hidden,false);assert.match(w.document.querySelector('#peerDetail').textContent,/A\/B错误 1 次/);assert.match(w.document.querySelector('#peerDetail').textContent,/120s/);assert.match(w.document.querySelector('#peerDetail').textContent,/BASE 2 · Lv.1/);assert.equal(JSON.stringify(t.currentProfile()),beforePeer);
 w.document.querySelector('#peerFilter').value='checked';w.document.querySelector('#peerFilter').onchange();assert.equal(w.document.querySelectorAll('[data-peer]').length,1);
 console.log('PASS peer wall: zero-R practice, status, badges, ordering, click details, filters, XSS escaping, own profile unchanged');
 t.cloudState.role='teacher';t.cloudState.user={id:'fixture-teacher'};fixture.class_roster=[{student_code:'1',student_name:'测试',user_id:'fixture-student'}];fixture.profiles=[{user_id:'fixture-student',r_points:8,xp:260}];fixture.progress_snapshots=[{user_id:'fixture-student',game_stats:{history:[{at:new Date().toISOString(),accuracy:90,avgTime:6}]}}];await t.loadTeacherDashboard('fixture-class');t.go('teacher');assert.match(w.document.querySelector('#teacherDataTable').textContent,/90%/);assert.match(w.document.querySelector('#teacherDataTable').textContent,/BASE 1 · Lv.2/);assert.equal(w.document.querySelectorAll('[data-reset-student]').length,1);assert.equal(t.rosterNameMap('1 张三\n2,李四',2)['2'],'李四');
 fixture.class_roster=['10','2','1'].map(student_code=>({student_code,student_name:'测试'+student_code}));await t.loadTeacherDashboard('fixture-class');
 for(const selector of ['#teacherRosterPreview .teacher-roster-item b','#teacherDataTable .teacher-data-row b','#teacherAccountsTable .teacher-account-row b'])assert.deepEqual(Array.from(w.document.querySelectorAll(selector),el=>el.textContent),['1号','2号','10号']);
 console.log('PASS teacher dashboard, roster parser and password-reset action retained (mock backend)');
 fixture.classes=[{id:'fixture-class',review_progress:{through:0,dates:{}}}];t.cloudState.classId='fixture-class';await w.reviewUI.loadTeacher('fixture-class');t.teacherSwitchTab('review');assert.ok(w.document.querySelector('#teacherPanelReview').classList.contains('active'));w.document.querySelector('#reviewThrough').value='1';w.document.querySelector('#reviewLearnedDate').value=w.KnowledgeReview.day();await w.document.querySelector('#saveReviewProgress').onclick();assert.equal(fixture.classes[0].review_progress.through,1);
 assert.equal(w.document.querySelector('#reviewLesson').value,'1','partial progress stays precise');assert.equal(w.document.querySelector('#reviewAdvanced').open,false);const oldDate=fixture.classes[0].review_progress.dates['ch2-1'];w.document.querySelector('#reviewLesson').value='13';w.document.querySelector('#reviewLesson').onchange();await w.document.querySelector('#saveReviewProgress').onclick();assert.equal(fixture.classes[0].review_progress.through,13);assert.equal(fixture.classes[0].review_progress.dates['ch2-1'],oldDate);w.document.querySelector('#reviewThrough').value='1';w.document.querySelector('#reviewThrough').onchange();await w.document.querySelector('#saveReviewProgress').onclick();
 student();t.cloudState.classId='fixture-class';t.go('knowledge');w.document.querySelector('#knowledge [data-go="rules"]').click();assert.ok(w.document.querySelector('#rules').classList.contains('active'));assert.ok(w.document.querySelector('.topbar [data-go="knowledge"]').classList.contains('active'));w.document.querySelector('#rules [data-go="review"]').click();assert.ok(w.document.querySelector('#review').classList.contains('active'));
 console.log('PASS knowledge hub branch clicks, parent navigation, simple lesson release and precise progress preservation');
 student();t.cloudState.classId='fixture-class';await w.reviewUI.open();assert.equal(w.document.querySelectorAll('#reviewPrompt input').length,2);assert.equal(w.document.querySelectorAll('#reviewNav button:not(:disabled)').length,1);
 const firstBlank=w.document.querySelector('#reviewPrompt input');assert.equal(firstBlank.getAttribute('autocapitalize'),'none');assert.equal(firstBlank.style.width,'');assert.equal(firstBlank.closest('label').style.getPropertyValue('--answer-width'),'2em');assert.equal(w.document.querySelector('#reviewSource').textContent,'教材 P13');assert.equal(w.document.querySelector('#reviewReveal').hidden,true);firstBlank.focus();w.document.querySelector('#reviewLanguage').click();assert.equal(w.document.querySelector('#reviewLetters').hidden,false);w.document.querySelector('[data-review-key="a"]').click();assert.equal(firstBlank.value,'a');w.document.querySelector('#reviewCase').click();w.document.querySelector('[data-review-key="B"]').click();assert.equal(firstBlank.value,'aB');const symbols=Array.from(w.document.querySelectorAll('#reviewSymbols button'));symbols.find(b=>b.textContent==='>').click();symbols.find(b=>b.textContent==='<').click();assert.equal(firstBlank.value,'aB><');firstBlank.setSelectionRange(0,2);w.document.querySelector('[data-review-key="C"]').click();assert.equal(firstBlank.value,'C><');w.document.querySelector('#reviewLanguage').click();assert.equal(w.document.querySelector('#reviewLetters').hidden,true);assert.equal(firstBlank.value,'C><','language switch preserves typed answer');
 await w.reviewUI.open('repair');const inputs=()=>Array.from(w.document.querySelectorAll('#reviewPrompt input'));inputs().forEach(x=>x.value='错');await w.reviewUI.submit();assert.match(w.document.querySelector('#reviewMode').textContent,/0\/5/);assert.equal(w.document.querySelector('#reviewReveal').hidden,false);assert.equal(w.document.querySelector('#reviewAnswer').hidden,true);const creditBeforeReveal=t.currentProfile().economy.credits;w.document.querySelector('#reviewReveal').click();assert.equal(w.document.querySelectorAll('#reviewAnswer li').length,2);assert.match(w.document.querySelector('#reviewAnswer').textContent,/正确答案：正数/);assert.match(w.document.querySelector('#reviewAnswer').textContent,/你的答案：错/);assert.equal(t.currentProfile().economy.credits,creditBeforeReveal);w.document.querySelector('#reviewReveal').click();assert.equal(w.document.querySelector('#reviewAnswer').hidden,true);
 console.log('PASS review input: answer-length fields and textbook pages, lowercase/uppercase keys, Chinese/English helpers, comparisons, selected replacement, safe answer reveal without rewards');

 for(let i=0;i<5;i++){w.reviewUI.next();inputs().forEach((x,j)=>x.value=j?'负数':'正数');await w.reviewUI.submit();}assert.match(w.document.querySelector('#reviewStatus').textContent,/已补签/);assert.equal(t.currentProfile().economy.credits,10);assert.equal(t.currentProfile().history[0].game,'knowledge');assert.match(w.document.querySelector('#historyList').textContent,/知识点回顾/);await w.reviewUI.submit();assert.equal(t.currentProfile().economy.credits,10);assert.ok(writes.some(x=>x.table==='daily_checkins'&&Array.isArray(x.row)&&x.row.some(d=>d.repaired)));assert.equal(writes.filter(x=>x.table==='progress_snapshots').at(-1).row.game_stats.history[0].game,'knowledge');
 w.reviewUI.next();fixture.classes[0].review_progress={through:0,dates:{}};inputs().forEach((x,j)=>x.value=j?'负数':'正数');await w.reviewUI.submit();assert.match(w.document.querySelector('#reviewStatus').textContent,/调整了学习进度/);assert.equal(t.currentProfile().economy.credits,10);
 console.log('PASS review UI: teacher release, locked directory, wrong resets, five correct repair, history/R/snapshot/repaired-date sync, duplicate submit, revoked progress');
 student();await w.document.querySelector('#logoutBtn').onclick();assert.equal(t.currentProfile(),null);assert.equal(t.cloudState.user,null);assert.equal(w.document.querySelector('#ringsFrame').getAttribute('src'),'about:blank');
 console.log('PASS logout clears current identity and old game frame');
 w.close();
})().catch(e=>{console.error(e);w.close();process.exitCode=1});
