const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');
const dom=new JSDOM('<!doctype html><div id="studentProfileContent"></div>',{runScripts:'outside-only',url:'https://test.local'}),w=dom.window;
w.RatioProfileBridge={earnedBadges:()=>['核心启动','数圈新探'],badgeImg:n=>'<img src="badge-'+n+'.png">',defaultAvatar:()=> 'default.png',today:()=>({points:22,checked:true,full:false})};
w.eval(fs.readFileSync('site/student-profile.js','utf8'));
const row={user_id:'u1',display_name:'17号小方',level:12,base_level:2,streak:5,badge_count:2,public_card_enabled:true,avatar_key:'level:12|frame:midautumn2026',custom_avatar:'assets/student-avatar-03.svg',public_training:{history:[{game:'rings',accuracy:90}]},profile_card:{theme:'detective',title:'分类侦探',featured_badges:['数圈新探'],show_recent:true}};
const chain={payload:null,update(payload){this.payload=payload;return this},eq(){return this},select(){return this},async single(){return {data:{...row,...this.payload},error:null}}};
const client={from(){return chain}};
w.StudentProfileCard.hydrate(row,{classId:'c1',className:'七年级29班',studentCode:'17'},client);
assert.equal(w.StudentProfileCard.portraits().length,10);
assert.equal(w.StudentProfileCard.avatarSrc('fallback'),'assets/student-avatar-03.svg');
assert.equal(w.StudentProfileCard.frameOn(),true);
w.StudentProfileCard.render();
const d=w.document;
assert.equal(d.querySelectorAll('[data-avatar-choice]').length,11);
assert.equal(d.querySelector('input[type="file"]'),null);
assert.doesNotMatch(d.querySelector('#studentProfileContent').textContent,/上传图片|上传 \/ 修改头像/);
assert.match(d.querySelector('#studentProfileContent').innerHTML,/midautumn-frame-2026-clear/);
const choice=d.querySelector('[data-avatar-choice="assets/student-avatar-08.svg"]');choice.click();
assert.equal(d.querySelector('.mission-avatar-img').getAttribute('src'),'assets/student-avatar-08.svg');
console.log('PASS student profile: 10 built-in portraits, no avatar upload, mission card and frame');w.close();